### PR TITLE
feat: Redesign about page

### LINKED ISSUE #152: Redesign About page
Right now, this page is super text-heavy. Let's see how we can share the same information in a less text-dense, more visual way. 

- simplify, make more visual
- add an impact section

### PR DESCRIPTION
**Pull request by sarahmonster**
Should look something along these lines when finished:

new-about-page

Close #152.

### CODE REVIEW

**Comment by sarahmonster** [comment]
At this stage, I'm happy enough to move forward with this—it's not perfect, but it's a good deal better than what we have right now. I'd love for you to have a look @tofumatt and let me know what should be tweaked/improved before we can merge it in! I'll keep picking away at it to get it better, but it's probably the sort of thing we can improve iteratively as well.

**Comment by sarahmonster** [comment]
Also the tests are failing and I'm not entirely sure why—`npm run lint` didn't give me any helpful output here! 😭

**Comment by tofumatt** [comment]
There's a `postinstall` bug with Nautilus that's totally on me. I'll get it sorted 👍🏻

**Review by tofumatt — APPROVED** [review]
I made a few tweaks to the text, mostly tightening things up.

I love it, and I say we ship it. Better than what we have by a lot! 😍

**Pull request merged**
