### PR TITLE
feat: Add draft of Mic Drop blog post

### PR DESCRIPTION
**Pull request by tofumatt**
This is good-to-go I think, but needs some decorative image love from you @sarahmonster.

Let me know if it's all good after you add the image. 😄

### CODE REVIEW

**Comment by sarahmonster** [comment]
Side note: for some reason I can't seem to see the tag on the post locally still, even though I've rebuilt things. Not sure if I need to run a special command or something to get it to show up?

**Comment by tofumatt** [comment]
`npm run clean && npm start` did it for me, seems like adding/removing tags requires a complete rebuild 😅

**Comment by sarahmonster** [comment]
Images added! I think this should be ready to ship if you're happy with it, finally! (Thank you for your patience.)

**Comment by sarahmonster** [comment]
Note: all images are showing up now, and all dates have been changed to today's date!

**Pull request merged**
