### PR TITLE
Add quote form

### PR DESCRIPTION
**Pull request by sarahmonster**
This basically just needs the sending part hooked up, but it's probably around 85% there.

### CODE REVIEW

**Comment by sarahmonster** [comment]
Overall, this looks great! I've made a few wee tweaks in terms of spacing and whatnot. I'm still torn about the positioning of the two buttons for the final step in the form, but we can tweak as needed as things go along.

The one thing here I'm not sure about is disabling the button until the user has filled in all the required fields. This feels a bit like an anti-pattern from a usability perspective, because  there's no indication of why the button is disabled, and why nothing happens if I click on it when it's disabled. 

Instead, I'd rather it be enabled the whole time, and if a user tries to click on it with empty required fields, those fields receive an indication that they need content.

**Comment by tofumatt** [comment]
Hmm, that's a fair point. Though the fields _are_ required, but I see what you mean. I'll make that change, and I'll actually remove the "Go back", as I'm not longer _hiding_ the old `<fieldset>`, just scrolling past it and showing the next step. Good call 👍

**Comment by sarahmonster** [comment]
Also: when I select any of the checkboxes in Chrome, I get scrolled up to the "About you" section, which is a wee bit disorienting.

**Comment by tofumatt** [comment]
Ah, I think I know the cause of that bug; I’ll get it sorted. Thanks!

**Comment by tofumatt** [comment]
Changes made! If you could have a quick look, and verify the checkbox focus styles are cool with you, I'll get this merged!

**Comment by sarahmonster** [comment]
I pushed two teensy little tweaks, but otherwise I think this is good to go! I might look into doing some more advanced form-validation type nonsense behaviours later, but I'd consider that wholly additive. This looks great. 🚀

**Pull request merged**
